name: Code Integration for frontend

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    paths:
      - '!WebAPI/src/**'
      - ClientApp/src/**
      - '!docs'
      - '!**/*.md'
      - '!**/*.txt'
      - '.github/workflows/code_integration_for_frontend.yml'
  workflow_dispatch:

defaults:
  run:
    working-directory: ClientApp

jobs:
  CI:
    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: build checking
      run: |
        yarn
        yarn build
